import type {
  Organization,
  User,
  BankAccount,
  BankStatement,
  Transaction,
  Invoice,
  ReconciliationMatch,
  ClassificationRule,
  Report,
  DashboardStats,
  MonthlyTrend,
  CategoryBreakdown,
  RecentActivity,
} from "./types";

// ── Organización ─────────────────────────────────────────────────────────────

export const mockOrganization: Organization = {
  id: "org-1",
  name: "Distribuidora Norte SRL",
  cuit: "30-71234567-9",
  fiscalCategory: "Responsable Inscripto",
  createdAt: new Date("2022-03-10"),
};

// ── Usuario actual ────────────────────────────────────────────────────────────

export const mockCurrentUser: User = {
  id: "user-1",
  orgId: "org-1",
  email: "martin.rodriguez@distribuidoranorte.com.ar",
  name: "Martín Rodríguez",
  role: "admin",
};

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: "user-2",
    orgId: "org-1",
    email: "carolina.gomez@distribuidoranorte.com.ar",
    name: "Carolina Gómez",
    role: "viewer",
  },
];

// ── Cuentas bancarias ─────────────────────────────────────────────────────────
// CBU: 22 dígitos  (3 banco + 4 sucursal + 1 verificador + 13 cuenta + 1 verificador)

export const mockBankAccounts: BankAccount[] = [
  {
    id: "ba-1",
    orgId: "org-1",
    bankName: "Banco Galicia",
    accountNumber: "4019871/2 070-3",
    cbu: "0070670230000712345691",
    currency: "ARS",
  },
  {
    id: "ba-2",
    orgId: "org-1",
    bankName: "Banco BIND",
    accountNumber: "5002341/7 322-1",
    cbu: "3220001230000098765437",
    currency: "ARS",
  },
];

// ── Extractos bancarios ───────────────────────────────────────────────────────
//
// stmt-1  Galicia Marzo 2026    completed   47 tx, 41 matched
// stmt-2  Galicia Febrero 2026  reconciled  52 tx, 48 matched
// stmt-3  BIND Marzo 2026       reviewing   31 tx, 18 matched
//
// Balances coherentes:
//   stmt-2 closing → stmt-1 opening
//   stmt-1 opening = 1.924.350,75
//   stmt-1 credits = 3.584.960,00
//   stmt-1 debits  = 2.983.740,00
//   stmt-1 closing = 1.924.350,75 + 3.584.960,00 - 2.983.740,00 = 2.525.570,75

export const mockStatements: BankStatement[] = [
  {
    id: "stmt-1",
    bankAccountId: "ba-1",
    uploadedBy: "user-1",
    periodStart: new Date("2026-03-01"),
    periodEnd: new Date("2026-03-31"),
    filePath: "/uploads/galicia-mar-2026.pdf",
    fileType: "pdf",
    status: "completed",
    closingBalance: 2_525_570.75,
    transactionCount: 47,
    matchedCount: 41,
    createdAt: new Date("2026-03-31"),
  },
  {
    id: "stmt-2",
    bankAccountId: "ba-1",
    uploadedBy: "user-1",
    periodStart: new Date("2026-02-01"),
    periodEnd: new Date("2026-02-28"),
    filePath: "/uploads/galicia-feb-2026.pdf",
    fileType: "pdf",
    status: "reconciled",
    closingBalance: 1_924_350.75,
    transactionCount: 52,
    matchedCount: 48,
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "stmt-3",
    bankAccountId: "ba-2",
    uploadedBy: "user-1",
    periodStart: new Date("2026-03-01"),
    periodEnd: new Date("2026-03-31"),
    filePath: "/uploads/bind-mar-2026.csv",
    fileType: "csv",
    status: "reviewing",
    closingBalance: 892_300.5,
    transactionCount: 31,
    matchedCount: 18,
    createdAt: new Date("2026-03-30"),
  },
];

// ── Transacciones — Galicia Marzo 2026 (stmt-1) ───────────────────────────────
//
// Muestra representativa de 28 de las 47 transacciones del período.
// Montos: negativos = débito, positivos = crédito.

export const mockTransactions: Transaction[] = [
  // ── Pagos a proveedores ──────────────────────────────────────────────────────
  {
    id: "tx-1",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-03"),
    description: "TRF LIMPIEZA TOTAL SA - FC A 0003-00007821",
    amount: -384_900.0,
    type: "debit",
    aiCategory: "pago_proveedor",
    aiConfidence: 0.97,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-1",
  },
  {
    id: "tx-2",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-04"),
    description: "TRF QUIMICOS DEL SUR SRL - FC A 0001-00003412",
    amount: -241_560.0,
    type: "debit",
    aiCategory: "pago_proveedor",
    aiConfidence: 0.95,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-2",
  },
  {
    id: "tx-3",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-05"),
    description: "DEBITO ENVASES PLASTICOS ARG SA - OC 9823",
    amount: -157_080.0,
    type: "debit",
    aiCategory: "pago_proveedor",
    aiConfidence: 0.93,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-3",
  },
  // ── Sueldos ──────────────────────────────────────────────────────────────────
  {
    id: "tx-4",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-10"),
    description: "SUELDO MARZO - LOPEZ J - CUIL 20-34512678-9",
    amount: -487_500.0,
    type: "debit",
    aiCategory: "salario",
    aiConfidence: 0.98,
    matchStatus: "confirmed",
  },
  {
    id: "tx-5",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-10"),
    description: "SUELDO MARZO - GARCIA P - CUIL 27-29876541-3",
    amount: -394_200.0,
    type: "debit",
    aiCategory: "salario",
    aiConfidence: 0.98,
    matchStatus: "confirmed",
  },
  {
    id: "tx-6",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-10"),
    description: "SUELDO MARZO - FERNANDEZ C - CUIL 20-30124567-8",
    amount: -312_800.0,
    type: "debit",
    aiCategory: "salario",
    aiConfidence: 0.97,
    matchStatus: "confirmed",
  },
  // ── Alquiler ─────────────────────────────────────────────────────────────────
  {
    id: "tx-7",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-01"),
    description: "DEBITO INMOBILIARIA NORTE SRL - ALQ DEPOSITO AV ENTRE RIOS 1240",
    amount: -520_000.0,
    type: "debit",
    aiCategory: "alquiler",
    aiConfidence: 0.91,
    matchStatus: "suggested",
    matchedInvoiceId: "inv-6",
  },
  // ── Servicios ─────────────────────────────────────────────────────────────────
  {
    id: "tx-8",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-12"),
    description: "EDESUR SA - FACTURA 8200341290 - SUMINISTRO ELECTRICO",
    amount: -38_450.0,
    type: "debit",
    aiCategory: "servicio",
    aiConfidence: 0.96,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-4",
  },
  {
    id: "tx-9",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-15"),
    description: "TELECOM ARGENTINA SA - FACTURA 0012-00987234",
    amount: -24_890.0,
    type: "debit",
    aiCategory: "servicio",
    aiConfidence: 0.94,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-5",
  },
  {
    id: "tx-28",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-06"),
    description: "SEGUROS ARG SA - POLIZA INCENDIO 00456823",
    amount: -47_800.0,
    type: "debit",
    // IA clasificó como "otros", usuario corrigió a "servicio"
    aiCategory: "otros",
    userCategory: "servicio",
    aiConfidence: 0.58,
    matchStatus: "suggested",
    matchedInvoiceId: "inv-17",
  },
  // ── Comisiones bancarias ──────────────────────────────────────────────────────
  {
    id: "tx-10",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-01"),
    description: "COMISION MANTENIMIENTO CTA CORRIENTE MAR/2026",
    amount: -3_250.0,
    type: "debit",
    aiCategory: "comision_bancaria",
    aiConfidence: 0.99,
    matchStatus: "confirmed",
  },
  {
    id: "tx-11",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-31"),
    description: "IMP DEBITOS Y CRED BANCARIOS LEY 25413 - MAR/2026",
    amount: -28_760.0,
    type: "debit",
    aiCategory: "comision_bancaria",
    aiConfidence: 0.96,
    matchStatus: "confirmed",
  },
  // ── Impuestos / retenciones / percepciones ────────────────────────────────────
  {
    id: "tx-12",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-07"),
    description: "AFIP - RET GANANCIAS 3RA CATEGORIA PER 02/2026",
    amount: -45_600.0,
    type: "debit",
    aiCategory: "retencion",
    aiConfidence: 0.95,
    matchStatus: "suggested",
  },
  {
    id: "tx-13",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-07"),
    description: "ARBA - PERCEPCION IIBB PROVINCIA BA 2.5% PER 02/2026",
    amount: -18_750.0,
    type: "debit",
    aiCategory: "percepcion",
    aiConfidence: 0.97,
    matchStatus: "confirmed",
  },
  {
    id: "tx-15",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-20"),
    description: "AFIP VEP IVA MENSUAL PERIODO 02/2026 - F731",
    amount: -78_200.0,
    type: "debit",
    aiCategory: "iva",
    aiConfidence: 0.94,
    matchStatus: "suggested",
  },
  // ── Transferencias ────────────────────────────────────────────────────────────
  {
    id: "tx-14",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-18"),
    description: "TRANSFERENCIA PROPIA - GALICIA ARS A CTA USD 0070670230000712345",
    amount: -200_000.0,
    type: "debit",
    aiCategory: "transferencia_interna",
    aiConfidence: 0.88,
    matchStatus: "confirmed",
  },
  // ── Cobros de clientes ────────────────────────────────────────────────────────
  {
    id: "tx-16",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-03"),
    description: "COBRO DEBIN - SUPERMERCADOS COTO CICSA CUIT 30-50123456-9",
    amount: 842_500.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.97,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-7",
  },
  {
    id: "tx-17",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-05"),
    description: "COBRO ECHEQ JUMBO RETAIL ARG SA - CHQ 0000043891",
    amount: 624_350.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.92,
    matchStatus: "suggested",
    matchedInvoiceId: "inv-8",
  },
  {
    id: "tx-18",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-08"),
    description: "ACRED TRANSFERENCIA - DISCO AHOLD ARGENTINA SA",
    amount: 387_650.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.91,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-12",
  },
  {
    id: "tx-19",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-10"),
    description: "COBRO DEBIN - CARREFOUR ARGENTINA SA CUIT 30-68580547-3",
    amount: 512_840.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.96,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-9",
  },
  {
    id: "tx-22",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-17"),
    description: "ACRED TRF - WALMART ARGENTINA SRL",
    amount: 289_700.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.94,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-10",
  },
  {
    id: "tx-24",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-21"),
    description: "COBRO ECHEQ - FARMACITY SA CHQ 0000128340",
    amount: 198_450.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.93,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-11",
  },
  {
    id: "tx-27",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-24"),
    description: "ACRED TRF - TIENDAS METRO SRL",
    amount: 156_300.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.89,
    matchStatus: "confirmed",
    matchedInvoiceId: "inv-15",
  },
  // ── Transferencias recibidas ──────────────────────────────────────────────────
  {
    id: "tx-20",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-12"),
    description: "TRF RECIBIDA - RODRIGUEZ M CUIT 20-29871234-5",
    amount: 350_000.0,
    type: "credit",
    // IA clasificó como transferencia interna; usuario corrigió a cobro cliente
    aiCategory: "transferencia_interna",
    userCategory: "cobro_cliente",
    aiConfidence: 0.62,
    matchStatus: "suggested",
    matchedInvoiceId: "inv-16",
  },
  {
    id: "tx-21",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-14"),
    description: "COBRO ECHEQ - MAKRO ARG SA CHQ 0000098712",
    amount: 125_400.0,
    type: "credit",
    aiCategory: "cobro_cliente",
    aiConfidence: 0.87,
    matchStatus: "suggested",
    matchedInvoiceId: "inv-16",
  },
  // ── Ambiguos / sin match ──────────────────────────────────────────────────────
  {
    id: "tx-23",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-20"),
    description: "DEPOSITO EFECTIVO SUCURSAL 070 CAJA 3",
    amount: 80_000.0,
    type: "credit",
    aiCategory: "otros",
    aiConfidence: 0.45,
    matchStatus: "unmatched",
  },
  {
    id: "tx-25",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-28"),
    description: "ACREDITACION INTERES PLAZO FIJO VTO 28/03/2026",
    amount: 12_350.0,
    type: "credit",
    aiCategory: "otros",
    aiConfidence: 0.52,
    matchStatus: "unmatched",
  },
  {
    id: "tx-26",
    statementId: "stmt-1",
    transactionDate: new Date("2026-03-28"),
    description: "REINTEGRO COMISION COBRADA EN EXCESO MAR/2026",
    amount: 5_420.0,
    type: "credit",
    aiCategory: "comision_bancaria",
    aiConfidence: 0.71,
    matchStatus: "confirmed",
  },
];

// ── Facturas ──────────────────────────────────────────────────────────────────
//
// IVA calculado como: net * 0,21 (Factura A con IVA discriminado)
// Factura B: IVA incluido en net, ivaAmount = 0

export const mockInvoices: Invoice[] = [
  // ── Compras a proveedores ─────────────────────────────────────────────────────
  {
    id: "inv-1",
    orgId: "org-1",
    invoiceNumber: "A 0003-00007821",
    type: "factura_a",
    counterpartyName: "Limpieza Total SA",
    counterpartyCuit: "30-65412387-5",
    netAmount: 318_099.17,
    ivaAmount: 66_800.83,
    totalAmount: 384_900.0,
    issueDate: new Date("2026-02-24"),
    dueDate: new Date("2026-03-26"),
    status: "matched",
  },
  {
    id: "inv-2",
    orgId: "org-1",
    invoiceNumber: "A 0001-00003412",
    type: "factura_a",
    counterpartyName: "Químicos del Sur SRL",
    counterpartyCuit: "30-71098234-1",
    netAmount: 199_636.36,
    ivaAmount: 41_923.64,
    totalAmount: 241_560.0,
    issueDate: new Date("2026-02-26"),
    dueDate: new Date("2026-03-28"),
    status: "matched",
  },
  {
    id: "inv-3",
    orgId: "org-1",
    invoiceNumber: "A 0002-00009823",
    type: "factura_a",
    counterpartyName: "Envases Plásticos Arg SA",
    counterpartyCuit: "30-60987654-3",
    netAmount: 129_818.18,
    ivaAmount: 27_261.82,
    totalAmount: 157_080.0,
    issueDate: new Date("2026-03-01"),
    dueDate: new Date("2026-03-31"),
    status: "matched",
  },
  // Factura de proveedor de mes anterior sin pagar aún (overdue)
  {
    id: "inv-14",
    orgId: "org-1",
    invoiceNumber: "A 0001-00003187",
    type: "factura_a",
    counterpartyName: "Químicos del Sur SRL",
    counterpartyCuit: "30-71098234-1",
    netAmount: 154_090.91,
    ivaAmount: 32_359.09,
    totalAmount: 186_450.0,
    issueDate: new Date("2026-01-28"),
    dueDate: new Date("2026-02-28"),
    status: "overdue",
  },
  // ── Servicios ─────────────────────────────────────────────────────────────────
  {
    id: "inv-4",
    orgId: "org-1",
    invoiceNumber: "B 0001-08200341",
    type: "factura_b",
    counterpartyName: "EDESUR SA",
    counterpartyCuit: "33-67815550-9",
    netAmount: 38_450.0,
    ivaAmount: 0,
    totalAmount: 38_450.0,
    issueDate: new Date("2026-03-08"),
    dueDate: new Date("2026-03-22"),
    status: "matched",
  },
  {
    id: "inv-5",
    orgId: "org-1",
    invoiceNumber: "B 0012-00987234",
    type: "factura_b",
    counterpartyName: "Telecom Argentina SA",
    counterpartyCuit: "30-70847239-9",
    netAmount: 24_890.0,
    ivaAmount: 0,
    totalAmount: 24_890.0,
    issueDate: new Date("2026-03-10"),
    dueDate: new Date("2026-03-25"),
    status: "matched",
  },
  {
    id: "inv-6",
    orgId: "org-1",
    invoiceNumber: "B 0001-00000412",
    type: "factura_b",
    counterpartyName: "Inmobiliaria Norte SRL",
    counterpartyCuit: "30-68234091-7",
    netAmount: 520_000.0,
    ivaAmount: 0,
    totalAmount: 520_000.0,
    issueDate: new Date("2026-02-28"),
    dueDate: new Date("2026-03-05"),
    status: "partially_matched",
  },
  {
    id: "inv-17",
    orgId: "org-1",
    invoiceNumber: "B 0002-00456823",
    type: "factura_b",
    counterpartyName: "Seguros Arg SA",
    counterpartyCuit: "30-69812340-5",
    netAmount: 47_800.0,
    ivaAmount: 0,
    totalAmount: 47_800.0,
    issueDate: new Date("2026-03-01"),
    dueDate: new Date("2026-03-15"),
    status: "partially_matched",
  },
  // ── Ventas a clientes ─────────────────────────────────────────────────────────
  {
    id: "inv-7",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000234",
    type: "factura_a",
    counterpartyName: "Supermercados Coto CICSA",
    counterpartyCuit: "30-50123456-9",
    netAmount: 696_280.99,
    ivaAmount: 146_219.01,
    totalAmount: 842_500.0,
    issueDate: new Date("2026-02-18"),
    dueDate: new Date("2026-03-04"),
    status: "matched",
  },
  {
    id: "inv-8",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000228",
    type: "factura_a",
    counterpartyName: "Jumbo Retail Argentina SA",
    counterpartyCuit: "30-70308853-5",
    netAmount: 563_099.17,
    ivaAmount: 118_250.83,
    totalAmount: 681_350.0,
    issueDate: new Date("2026-02-20"),
    dueDate: new Date("2026-03-07"),
    // tx-17 cobró 624.350 de un total de 681.350 → pago parcial
    status: "partially_matched",
  },
  {
    id: "inv-9",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000241",
    type: "factura_a",
    counterpartyName: "Carrefour Argentina SA",
    counterpartyCuit: "30-68580547-3",
    netAmount: 423_834.71,
    ivaAmount: 89_005.29,
    totalAmount: 512_840.0,
    issueDate: new Date("2026-02-25"),
    dueDate: new Date("2026-03-11"),
    status: "matched",
  },
  {
    id: "inv-10",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000219",
    type: "factura_a",
    counterpartyName: "Walmart Argentina SRL",
    counterpartyCuit: "30-67799498-4",
    netAmount: 239_504.13,
    ivaAmount: 50_195.87,
    totalAmount: 289_700.0,
    issueDate: new Date("2026-03-05"),
    dueDate: new Date("2026-03-19"),
    status: "matched",
  },
  {
    id: "inv-11",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000243",
    type: "factura_a",
    counterpartyName: "Farmacity SA",
    counterpartyCuit: "30-69984221-3",
    netAmount: 164_090.91,
    ivaAmount: 34_359.09,
    totalAmount: 198_450.0,
    issueDate: new Date("2026-03-10"),
    dueDate: new Date("2026-03-24"),
    status: "matched",
  },
  {
    id: "inv-12",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000231",
    type: "factura_a",
    counterpartyName: "Disco Ahold Argentina SA",
    counterpartyCuit: "30-68763406-7",
    netAmount: 320_371.9,
    ivaAmount: 67_278.1,
    totalAmount: 387_650.0,
    issueDate: new Date("2026-02-22"),
    dueDate: new Date("2026-03-09"),
    status: "matched",
  },
  {
    id: "inv-15",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000247",
    type: "factura_a",
    counterpartyName: "Tiendas Metro SRL",
    counterpartyCuit: "30-70912345-6",
    netAmount: 129_173.55,
    ivaAmount: 27_126.45,
    totalAmount: 156_300.0,
    issueDate: new Date("2026-03-15"),
    dueDate: new Date("2026-03-26"),
    status: "matched",
  },
  // Factura de venta cobrada en dos pagos agrupados (tx-20 + tx-21)
  {
    id: "inv-16",
    orgId: "org-1",
    invoiceNumber: "A 0001-00000235",
    type: "factura_a",
    counterpartyName: "Makro Argentina SA",
    counterpartyCuit: "30-71234098-2",
    netAmount: 392_892.56,
    ivaAmount: 82_507.44,
    totalAmount: 475_400.0,
    issueDate: new Date("2026-02-28"),
    dueDate: new Date("2026-03-15"),
    // 350.000 + 125.400 = 475.400 → dos pagos cubrieron el total
    status: "partially_matched",
  },
  // ── Nota de crédito ───────────────────────────────────────────────────────────
  {
    id: "inv-13",
    orgId: "org-1",
    invoiceNumber: "NC A 0003-00000089",
    type: "nota_credito",
    counterpartyName: "Limpieza Total SA",
    counterpartyCuit: "30-65412387-5",
    netAmount: -15_000.0,
    ivaAmount: -3_150.0,
    totalAmount: -18_150.0,
    issueDate: new Date("2026-03-14"),
    dueDate: new Date("2026-03-14"),
    status: "pending",
  },
];

// ── Matches de conciliación ───────────────────────────────────────────────────

export const mockMatches: ReconciliationMatch[] = [
  // Exact — confirmados por usuario
  {
    id: "match-1",
    transactionId: "tx-1",
    invoiceId: "inv-1",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.98,
    status: "confirmed",
    createdAt: new Date("2026-03-31"),
  },
  {
    id: "match-2",
    transactionId: "tx-2",
    invoiceId: "inv-2",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.97,
    status: "confirmed",
    createdAt: new Date("2026-03-31"),
  },
  {
    id: "match-3",
    transactionId: "tx-3",
    invoiceId: "inv-3",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.95,
    status: "confirmed",
    createdAt: new Date("2026-03-31"),
  },
  {
    id: "match-4",
    transactionId: "tx-8",
    invoiceId: "inv-4",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.98,
    status: "confirmed",
    createdAt: new Date("2026-03-29"),
  },
  {
    id: "match-5",
    transactionId: "tx-9",
    invoiceId: "inv-5",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.96,
    status: "confirmed",
    createdAt: new Date("2026-03-29"),
  },
  {
    id: "match-6",
    transactionId: "tx-16",
    invoiceId: "inv-7",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.99,
    status: "confirmed",
    createdAt: new Date("2026-03-28"),
  },
  {
    id: "match-7",
    transactionId: "tx-18",
    invoiceId: "inv-12",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.97,
    status: "confirmed",
    createdAt: new Date("2026-03-28"),
  },
  {
    id: "match-8",
    transactionId: "tx-19",
    invoiceId: "inv-9",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.96,
    status: "confirmed",
    createdAt: new Date("2026-03-28"),
  },
  {
    id: "match-9",
    transactionId: "tx-22",
    invoiceId: "inv-10",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.95,
    status: "confirmed",
    createdAt: new Date("2026-03-29"),
  },
  {
    id: "match-10",
    transactionId: "tx-24",
    invoiceId: "inv-11",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.94,
    status: "confirmed",
    createdAt: new Date("2026-03-29"),
  },
  {
    id: "match-11",
    transactionId: "tx-27",
    invoiceId: "inv-15",
    confirmedBy: "user-1",
    matchType: "exact",
    confidenceScore: 0.91,
    status: "confirmed",
    createdAt: new Date("2026-03-30"),
  },
  // Partial — tx cobró menos que el total de la factura
  {
    id: "match-12",
    transactionId: "tx-17",
    invoiceId: "inv-8",
    matchType: "partial",
    confidenceScore: 0.74,
    status: "suggested",
    createdAt: new Date("2026-03-30"),
  },
  {
    id: "match-13",
    transactionId: "tx-7",
    invoiceId: "inv-6",
    matchType: "partial",
    confidenceScore: 0.68,
    status: "suggested",
    createdAt: new Date("2026-03-30"),
  },
  // Grouped — dos transacciones cubren una misma factura
  {
    id: "match-14",
    transactionId: "tx-20",
    invoiceId: "inv-16",
    matchType: "grouped",
    confidenceScore: 0.71,
    status: "suggested",
    createdAt: new Date("2026-03-30"),
  },
  {
    id: "match-15",
    transactionId: "tx-21",
    invoiceId: "inv-16",
    matchType: "grouped",
    confidenceScore: 0.69,
    status: "suggested",
    createdAt: new Date("2026-03-30"),
  },
];

// ── Reglas de clasificación ───────────────────────────────────────────────────

export const mockRules: ClassificationRule[] = [
  {
    id: "rule-1",
    orgId: "org-1",
    pattern: "COMISION.*MANTENIMIENTO",
    category: "comision_bancaria",
    source: "ai_generated",
    timesApplied: 38,
  },
  {
    id: "rule-2",
    orgId: "org-1",
    pattern: "SUELDO.*MARZO|SUELDO.*CUIL",
    category: "salario",
    source: "user_defined",
    timesApplied: 31,
  },
  {
    id: "rule-3",
    orgId: "org-1",
    pattern: "AFIP.*VEP|AFIP.*RET",
    category: "impuesto",
    source: "user_defined",
    timesApplied: 24,
  },
  {
    id: "rule-4",
    orgId: "org-1",
    pattern: "ARBA.*PERCEPCION|PERCEPCION.*IIBB",
    category: "percepcion",
    source: "ai_generated",
    timesApplied: 19,
  },
  {
    id: "rule-5",
    orgId: "org-1",
    pattern: "RET.*GANANCIAS.*3RA",
    category: "retencion",
    source: "ai_generated",
    timesApplied: 14,
  },
  {
    id: "rule-6",
    orgId: "org-1",
    pattern: "IMP DEBITOS.*LEY 25413",
    category: "comision_bancaria",
    source: "ai_generated",
    timesApplied: 28,
  },
  {
    id: "rule-7",
    orgId: "org-1",
    pattern: "EDESUR|EDENOR|LUZ Y FUERZA",
    category: "servicio",
    source: "user_defined",
    timesApplied: 12,
  },
  {
    id: "rule-8",
    orgId: "org-1",
    pattern: "COBRO DEBIN|COBRO ECHEQ|ACRED TRF",
    category: "cobro_cliente",
    source: "ai_generated",
    timesApplied: 87,
  },
  {
    id: "rule-9",
    orgId: "org-1",
    pattern: "TRF.*SA$|TRF.*SRL$|DEBITO.*SA$",
    category: "pago_proveedor",
    source: "ai_generated",
    timesApplied: 53,
  },
  {
    id: "rule-10",
    orgId: "org-1",
    pattern: "DEBITO.*ALQ|INMOBILIARIA",
    category: "alquiler",
    source: "user_defined",
    timesApplied: 9,
  },
];

// ── Reportes ──────────────────────────────────────────────────────────────────

export const mockReports: Report[] = [
  {
    id: "report-1",
    orgId: "org-1",
    statementId: "stmt-2",
    reportType: "conciliation",
    filePath: "/reports/conciliacion-galicia-feb-2026.pdf",
    summaryData: {
      totalIncome: 4_712_300.0,
      totalExpense: 3_861_990.25,
      matchedTransactions: 48,
      unmatchedTransactions: 2,
      pendingReview: 2,
    },
    generatedAt: new Date("2026-03-04"),
  },
  {
    id: "report-2",
    orgId: "org-1",
    statementId: "stmt-2",
    reportType: "tax_detail",
    filePath: "/reports/impuestos-feb-2026.pdf",
    summaryData: {
      totalIncome: 4_712_300.0,
      totalExpense: 3_861_990.25,
      matchedTransactions: 48,
      unmatchedTransactions: 2,
      pendingReview: 0,
    },
    generatedAt: new Date("2026-03-05"),
  },
];

// ── Dashboard stats ───────────────────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  totalProcessed: 130,  // transacciones procesadas en el período activo
  aiAccuracy: 94.2,     // % de clasificaciones correctas sin corrección manual
  timeSaved: 18.5,      // horas estimadas ahorradas vs. proceso manual
  pendingReview: 13,    // transacciones que esperan revisión humana
};

// ── Tendencia mensual (últimos 6 meses) ──────────────────────────────────────

export const mockMonthlyTrend: MonthlyTrend[] = [
  {
    month: "Oct 2025",
    income: 3_850_000,
    expense: 3_121_400,
    matched: 89,
    total: 96,
  },
  {
    month: "Nov 2025",
    income: 4_215_600,
    expense: 3_448_900,
    matched: 93,
    total: 100,
  },
  {
    month: "Dic 2025",
    income: 5_102_300,
    expense: 4_198_750,
    matched: 107,
    total: 115,
  },
  {
    month: "Ene 2026",
    income: 3_601_800,
    expense: 3_052_100,
    matched: 86,
    total: 93,
  },
  {
    month: "Feb 2026",
    income: 4_712_300,
    expense: 3_861_990,
    matched: 101,
    total: 108,
  },
  {
    month: "Mar 2026",
    income: 3_584_960,
    expense: 2_983_740,
    matched: 41,
    total: 47, // en curso
  },
];

// ── Distribución por categoría (Marzo 2026 — egresos) ────────────────────────
// Calculado sobre el total de egresos: $2.983.740

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  {
    category: "salario",
    amount: 1_194_500,
    count: 3,
    percentage: 40.0,
  },
  {
    category: "pago_proveedor",
    amount: 783_540,
    count: 3,
    percentage: 26.3,
  },
  {
    category: "alquiler",
    amount: 520_000,
    count: 1,
    percentage: 17.4,
  },
  {
    category: "transferencia_interna",
    amount: 200_000,
    count: 1,
    percentage: 6.7,
  },
  {
    category: "iva",
    amount: 78_200,
    count: 1,
    percentage: 2.6,
  },
  {
    category: "servicio",
    amount: 111_140,
    count: 3,
    percentage: 3.7,
  },
  {
    category: "retencion",
    amount: 45_600,
    count: 1,
    percentage: 1.5,
  },
  {
    category: "comision_bancaria",
    amount: 32_010,
    count: 2,
    percentage: 1.1,
  },
  {
    category: "percepcion",
    amount: 18_750,
    count: 1,
    percentage: 0.6,
  },
];

// ── Actividad reciente ────────────────────────────────────────────────────────

export const mockRecentActivity: RecentActivity[] = [
  {
    id: "act-1",
    type: "upload",
    description: "Se subió el extracto de BIND Marzo 2026 (31 transacciones)",
    timestamp: new Date("2026-03-30T10:14:00"),
    meta: { statementId: "stmt-3", bankName: "Banco BIND" },
  },
  {
    id: "act-2",
    type: "classification",
    description: "IA clasificó 31 transacciones del extracto BIND Marzo 2026",
    timestamp: new Date("2026-03-30T10:16:00"),
    meta: { statementId: "stmt-3", accuracy: 91.2 },
  },
  {
    id: "act-3",
    type: "match_confirmed",
    description: "Confirmado: Tiendas Metro SRL → FC A 0001-00000247 ($156.300)",
    timestamp: new Date("2026-03-30T09:42:00"),
    meta: { matchId: "match-11", amount: 156_300 },
  },
  {
    id: "act-4",
    type: "match_confirmed",
    description: "Confirmado: Farmacity SA → FC A 0001-00000243 ($198.450)",
    timestamp: new Date("2026-03-29T17:05:00"),
    meta: { matchId: "match-10", amount: 198_450 },
  },
  {
    id: "act-5",
    type: "match_suggested",
    description: "IA sugirió match parcial: Jumbo Retail → FC A 0001-00000228 (91,7% cobrado)",
    timestamp: new Date("2026-03-29T16:58:00"),
    meta: { matchId: "match-12", confidence: 0.74 },
  },
  {
    id: "act-6",
    type: "match_suggested",
    description: "IA sugirió match agrupado: 2 transferencias → FC Makro Argentina ($475.400)",
    timestamp: new Date("2026-03-29T16:55:00"),
    meta: { matchIds: ["match-14", "match-15"], invoiceId: "inv-16" },
  },
  {
    id: "act-7",
    type: "match_confirmed",
    description: "Confirmado: Supermercados Coto → FC A 0001-00000234 ($842.500)",
    timestamp: new Date("2026-03-28T14:30:00"),
    meta: { matchId: "match-6", amount: 842_500 },
  },
  {
    id: "act-8",
    type: "report_generated",
    description: "Generado reporte de conciliación Galicia Febrero 2026",
    timestamp: new Date("2026-03-25T11:20:00"),
    meta: { reportId: "report-1", statementId: "stmt-2" },
  },
  {
    id: "act-9",
    type: "rule_created",
    description: "Nueva regla creada por usuario: 'SUELDO.*CUIL' → salario",
    timestamp: new Date("2026-03-24T09:15:00"),
    meta: { ruleId: "rule-2", source: "user_defined" },
  },
  {
    id: "act-10",
    type: "match_confirmed",
    description: "Confirmado: EDESUR SA → FC B 0001-08200341 ($38.450)",
    timestamp: new Date("2026-03-28T14:28:00"),
    meta: { matchId: "match-4", amount: 38_450 },
  },
];
